on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4      

      - name: Save cache (node_modules)
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run npm install
        run: npm install

      - name: Run Build
        run: npm run build

  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    strategy:
        matrix:
            browser: [chrome, edge]

    steps:
      - uses: actions/checkout@v4
      - name: Restore cache (node_modules)
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-videos-${{ matrix.browser }}
            path: /cypress/videos

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots 
          path: /cypress/screenshots

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
            cd ${{ secrets.APP_DIR }}
            git pull origin main
            npm install
            npm run build
            pm2 reload all