on: [push]
jobs:
    # job: 
    #   runs-on: ubuntu-latest
    #   steps: 
    #   - uses: actions/checkout@v4
    #   - name: Run npm ci
    #     run: npm install

    #   - name: Run Build
    #     run: npm run build

    #   - name: Run Test
    #     run: npm run e2e:headless

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4      

      - name: Save cache (node_modules)
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run npm install
        run: npm install

      - name: Run Build
        run: npm run build

  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    strategy:
        matrix:
            browser: [chrome, firefox, edge]

    steps:
      - uses: actions/checkout@v4
      - name: Restore cache (node_modules)
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
            name: cypress-videos-${{ matrix.browser }}
            path: /cypress/videos

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots 
          path: /cypress/screenshots
