name: Build & Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & build
        run: |
          npm install
          npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USERNAME }}
          key: ${{ secrets.APP_KEY }}
          port: 22
          script: |
            mkdir -p ~/myapp
            cd ~/myapp
            # On efface l'ancien code (optionnel)
            rm -rf *
            # On transfère les fichiers
            echo "Transfert des fichiers…"
            cat > deploy.zip << 'EOF'
            ${{ steps.build.outputs.artifact || '' }}
            EOF
            # à remplacer par scp ou git clone, ex :
            git pull origin main
            npm install --production
            pm2 restart myapp || pm2 start npm --name myapp -- start
