on: [push]
jobs:
    # job: 
    #   runs-on: ubuntu-latest
    #   steps: 
    #   - uses: actions/checkout@v4
    #   - name: Run npm ci
    #     run: npm install

    #   - name: Run Build
    #     run: npm run build

    #   - name: Run Test
    #     run: npm run e2e:headless

  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4      
      - name: Run npm install
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Save cache (node_modules)
        uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache (node_modules)
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}--node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run Test
        run: npm run e2e:headless

